version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $BASE_IMAGE_URI | cut -d'/' -f1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $TARGET_REPO_URI:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $TARGET_REPO_URI:latest
      - printf '[{"name":"app_container","imageUri":"%s"}]\n' "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG" > imagedefinitions.json
  artifacts:
    files:
      - imagedefinitions.json 
